name: TextNinjaUno
favicon: null
layout_spectrum: 0
typography_spectrum: 0.20616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f1531d'
    - '#545152'
    - '#a2a0a1'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
