name: TextNinjaUno
favicon: null
layout_spectrum: 0.857296478934586
typography_spectrum: 0.8653236739337444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7872151506599039
  lightness: 0.4707914765458554
  saturation: 0.3695020298473537
  rhythmicContrast: 0.06265638279728591
purpose: []
